# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180618_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundperson',
            name='Details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='foundperson',
            name='FoundPersonImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='Details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='MissingPersonImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
