# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180621_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundperson',
            name='FoundPersonImage',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='missingperson',
            name='MissingPersonImage',
            field=models.ImageField(upload_to='img'),
        ),
    ]
